# Generated by Django 5.2.13 on 2026-05-05 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rava_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='credits',
            field=models.IntegerField(default=100, help_text='Number of credits the user owns'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='current_plan',
            field=models.CharField(default='free plan', help_text='Current subscription plan of the user', max_length=50),
        ),
        migrations.AddField(
            model_name='generatedaudio',
            name='credits_consumed',
            field=models.PositiveIntegerField(default=0, help_text='Credits consumed to generate this audio'),
        ),
    ]
